[package]
name = "mdbook-diagrams"
version = "0.1.0"
edition = "2024"
description = "Mermaid diagram generator for mdbook"
repository = "https://github.com/chabun314/mdbook-diagrams"

[dependencies]
mdbook = "0.4.37"
anyhow = "1.0"
mdbook-preprocessor-boilerplate = "0.1.2"
regex = "1.10.5"
uuid = { version = "1.9.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
